version: '3.6'

networks:
  net:
    driver: overlay
    attachable: true
  es_elastic:
    external: true

services:

  cdrpr-berlin:
    image: matjaz99/cdrpr:2.0
    networks:
      - net
      - es_elastic
    ports:
      - 9099:9099
    environment:
      - CDRPR_THREADS=32
      - CDRPR_BULK_SIZE=7000
      - CDRPR_DEBUG_ENABLED=false
      # - CDRPR_ES_URL=http://172.29.6.6:9200/cdrs/_bulk?pretty
      - CDRPR_ES_URL=http://172.29.6.6:9200/cdr_aggs/_bulk?pretty
      - CDRPR_EXIT=false
      - CDRPR_SIMULATOR_MODE=STORE_AGGREGATED_CALLS
      - CDRPR_SIMULATOR_STORAGE_TYPE=ELASTICSEARCH
      - CDRPR_SIMULATOR_NODEID=Berlin
      - CDRPR_SIMULATOR_DELAY=30
      - CDRPR_SIMULATOR_CALL_REASON=0
      - CDRPR_SIMULATOR_ANUM_START=10000000
      - CDRPR_SIMULATOR_ANUM_RANGE=9999999
      - CDRPR_SIMULATOR_BNUM_START=80000000
      - CDRPR_SIMULATOR_BNUM_RANGE=9999999
      - CDRPR_SIMULATOR_MINIMUM_DATA=true
    deploy:
      mode: replicated
      replicas: 1

  cdrpr-london:
    image: matjaz99/cdrpr:2.0
    networks:
      - net
      - es_elastic
    ports:
      - 9098:9099
    environment:
      - CDRPR_THREADS=32
      - CDRPR_BULK_SIZE=5000
      - CDRPR_DEBUG_ENABLED=false
      # - CDRPR_ES_URL=http://172.29.6.6:9200/cdrs/_bulk?pretty
      - CDRPR_ES_URL=http://172.29.6.6:9200/cdr_aggs/_bulk?pretty
      - CDRPR_EXIT=false
      - CDRPR_SIMULATOR_MODE=STORE_AGGREGATED_CALLS
      - CDRPR_SIMULATOR_STORAGE_TYPE=ELASTICSEARCH
      - CDRPR_SIMULATOR_NODEID=London
      - CDRPR_SIMULATOR_DELAY=25
      - CDRPR_SIMULATOR_CALL_REASON=0
      - CDRPR_SIMULATOR_ANUM_START=20000000
      - CDRPR_SIMULATOR_ANUM_RANGE=9999999
      - CDRPR_SIMULATOR_BNUM_START=40000000
      - CDRPR_SIMULATOR_BNUM_RANGE=9999999
      - CDRPR_SIMULATOR_MINIMUM_DATA=true
    deploy:
      mode: replicated
      replicas: 1

  cdrpr-moscow:
    image: matjaz99/cdrpr:2.0
    networks:
      - net
      - es_elastic
    ports:
      - 9097:9099
    environment:
      - CDRPR_THREADS=64
      - CDRPR_BULK_SIZE=5000
      - CDRPR_DEBUG_ENABLED=false
      - CDRPR_ES_URL=http://172.29.6.6:9200/cdrs/_bulk?pretty
      - CDRPR_EXIT=false
      - CDRPR_SIMULATOR_MODE=true
      - CDRPR_SIMULATOR_NODEID=Moscow
      - CDRPR_SIMULATOR_DELAY=20
      - CDRPR_SIMULATOR_CALL_REASON=0
      - CDRPR_SIMULATOR_ANUM_START=70000000
      - CDRPR_SIMULATOR_ANUM_RANGE=19999999
      - CDRPR_SIMULATOR_BNUM_START=60000000
      - CDRPR_SIMULATOR_BNUM_RANGE=19999999
      - CDRPR_SIMULATOR_MINIMUM_DATA=true
    deploy:
      mode: replicated
      replicas: 1
