version: '3.6'

networks:
  net:
    driver: overlay
    attachable: true
  es_elastic:
    external: true

services:

  cdrpr:
    image: matjaz99/cdrpr:2.0
    networks:
      - net
      - es_elastic
    environment:
      - CDRPR_THREADS=64
      - CDRPR_BULK_SIZE=5000
      - CDRPR_DEBUG_ENABLED=false
      - CDRPR_ES_URL=http://192.168.1.106:9200/cdrs/_bulk?pretty
      - CDRPR_EXIT=false
      - CDRPR_SIMULATOR_MODE=true
      - CDRPR_SIMULATOR_NODEID=Berlin
      - CDRPR_SIMULATOR_DELAY=100
      - CDRPR_SIMULATOR_CALL_REASON=0
      - CDRPR_SIMULATOR_ANUM_START=1000000
      - CDRPR_SIMULATOR_ANUM_RANGE=999999
      - CDRPR_SIMULATOR_BNUM_START=8000000
      - CDRPR_SIMULATOR_BNUM_RANGE=999999
    deploy:
      mode: replicated
      replicas: 1
