global:
  scrape_interval:     15s
  evaluation_interval: 15s

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
    monitor: 'prometheus'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['192.168.0.170:9100', '192.168.1.170:9100']

  - job_name: 'metricslib'
    static_configs:
      - targets: ['localhost:9099', '192.168.0.170:9099', '192.168.1.170:9099', '192.168.0.18:9099', '192.168.1.222:9099']
