version: '3.6'

networks:
  net:
    driver: overlay
    attachable: true

services:
  cdrsim:
    image: matjaz99/cdrpr:2.1
    networks:
      - net
    ports:
      - 9099:9099
    environment:
      - CDRPR_THREADS=48
      - CDRPR_SIMULATOR_DELAY=30
      - CDRPR_SEND_INTERVAL_SEC=60
      - CDRPR_ES_HOST=172.29.6.6
      - CDRPR_ES_PORT=9200
      # if true, create ILM (pmon_ilm_policy) manually before running simulator!
      # if false, create mapping manually before running simulator (if you want to use timestamp)!
      - CDRPR_ES_AUTO_CREATE_INDEX=true
      - CDRPR_ES_INDEX_PREFIX=
      - CDRPR_ES_NUMBER_OF_SHARDS=1
      - CDRPR_ES_NUMBER_OF_REPLICAS=0
      - CDRPR_DUMP_TO_FILE=false
    volumes:
      - /var/log:/opt/log
    deploy:
      mode: replicated
      replicas: 1

