version: '3.6'

networks:
  net:
    driver: overlay
    attachable: true

volumes:
  data01:
    driver: local

configs:
  kibana_config:
    file: ./kibana.yml

services:

  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.2
    environment:
      - discovery.type=single-node
      #- "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "ES_JAVA_OPTS=-Xms4g -Xmx4g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - net
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.hostname == mcrk-docker-1
          #- node.hostname == $(hostname)

  kibana:
    image: docker.elastic.co/kibana/kibana:7.9.2
    networks:
      - net
    ports:
      - 5601:5601
    #volumes:
    #  - ./kibana.yml:/usr/share/kibana/config/kibana.yml
    configs:
      - source: kibana_config
        target: /usr/share/kibana/config/kibana.yml
    environment:
      SERVER_NAME: kibana.example.org
      ELASTICSEARCH_HOSTS: http://es01:9200
