version: '3.6'

networks:
  net:
    driver: overlay
    attachable: true

services:
  cdrsim:
    #image: matjaz99/cdrpr:2.1
    # support for ssl in 2.2
    image: matjaz99/cdrpr:2.2
    networks:
      - net
    ports:
      - 9099:9099
    environment:
      - CDRPR_SIMULATOR_MODE=CDR_TO_KAFKA
      - CDRPR_SEND_INTERVAL_SEC=60
      - CDRPR_ES_SCHEMA=http
      - CDRPR_ES_HOST=172.29.6.6
      - CDRPR_ES_PORT=9200
      - CDRPR_ES_BASIC_USER=admin
      - CDRPR_ES_BASIC_PASS=admin
      # if true, create ILM (pmon_ilm_policy) manually before running simulator!
      # if false, create mapping manually before running simulator (if you want to use timestamp)!
      - CDRPR_ES_AUTO_CREATE_INDEX=true
      - CDRPR_ES_INDEX_PREFIX=
      - CDRPR_ES_NUMBER_OF_SHARDS=1
      - CDRPR_ES_NUMBER_OF_REPLICAS=0
      - CDRPR_DUMP_TO_FILE=false
      - CDRPR_KAFKA_BOOTSTRAP_SERVER=centosvm:9092
      - CDRPR_EXIT_WHEN_DONE=false
    volumes:
      - /var/log:/opt/log
      - cdr_input_dir:/opt/cdr_input_dir
      - cdr_output_dir:/opt/cdr_output_dir
    deploy:
      mode: replicated
      replicas: 1

