version: '3.6'

networks:
  net:
    driver: overlay
    attachable: true

services:
  heartbeat:
    image: docker.elastic.co/beats/heartbeat:7.8.0
    command:
      - 'setup'
    environment:
      - setup.kibana.host=192.168.1.170:5601
      - output.elasticsearch.hosts=["192.168.1.170:9200"]
    networks:
      - net
    deploy:
      mode: replicated
      replicas: 1