version: '3.6'

networks:
  net:
    driver: overlay
    attachable: true

services:
  cdrsim:
    image: matjaz99/cdrpr:4.0
    networks:
      - net
    ports:
      - 9099:9099
    environment:
      - CDRPR_SIMULATOR_MODE=GENERATE_CDR_AND_STORE_ALL_TO_ES
    volumes:
      - /var/log:/opt/log
      #- ./dump:/opt/dump
      - ../config/cdrpr.properties:/opt/config/cdrpr.properties
    deploy:
      mode: replicated
      replicas: 1

