version: '3.6'

networks:
  net:
    driver: overlay
    attachable: true

volumes:
  grafana_storage:
    driver: local
  pgadmin_storage:
    driver: local

services:

  postgres:
    image: postgres:11.8
    networks:
      - net
    ports:
      - 5432:5432
    volumes:
      - /storage/postgres/cdraggs_data:/var/lib/postgresql/data
      #- /home/postgres/cdraggs_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: cdraggs
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: object00
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
        #- node.labels.node-type == storage
          - node.hostname == mcrk-docker-1

  pgadmin4:
    image: dpage/pgadmin4:4.23
    networks:
      - net
    ports:
      - 8081:80
      - 8443:443
    environment:
      PGADMIN_DEFAULT_EMAIL: test@example.com
      PGADMIN_DEFAULT_PASSWORD: iskratel
    volumes:
      #- pgadmin_storage:/root/.pgadmin
      - pgadmin_storage:/var/lib/pgadmin
    deploy:
      mode: replicated
      replicas: 1

  grafana:
    image: grafana/grafana:6.7.1
    networks:
      - net
    ports:
      - 3000:3000
    environment:
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource,grafana-piechart-panel,corpglory-progresslist-panel,camptocamp-prometheus-alertmanager-datasource,michaeldmoore-multistat-panel,briangann-gauge-panel,flant-statusmap-panel,jdbranham-diagram-panel,natel-discrete-panel,natel-plotly-panel
    volumes:
      - grafana_storage:/var/lib/grafana
    deploy:
      mode: replicated
      replicas: 1