version: '3.6'

networks:
  net:
    driver: overlay
    attachable: true

services:
  cdrsim:
    image: matjaz99/cdrpr:2.0
    networks:
      - net
    ports:
      - 9099:9099
    environment:
      - CDRPR_THREADS=32
      - CDRPR_SIMULATOR_DELAY=60
      - CDRPR_SEND_INTERVAL_SEC=60
      - CDRPR_ES_HOST=172.29.6.6
      - CDRPR_ES_PORT=9200
      - CDRPR_ES_AUTO_CREATE_INDEX=false
      - CDRPR_DUMP_TO_FILE=false
    deploy:
      mode: replicated
      replicas: 1

