{
 "title": "CDRAGGS_PG_calls_by_cause",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Calls by cause",
   "type": "graph",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS time, COUNT(cause), cause\nFROM\n  m_countbycrc\nGROUP BY time, cause\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Total calls by cause",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "rawSql": "SELECT\n  cause AS \"cause\",\n  sum(value) AS \"value\"\nFROM m_countbycrc\nGROUP BY cause\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Total calls by cause (barchart)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  cause AS \"cause\",\n  sum(value)\nFROM m_countbycrc\nGROUP BY cause"
    }
   ]
  }
 ]
}