{
 "title": "CDRAGGS_PG_general",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Last insert count (m_countbycrc)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT timestamp as time,\n  COUNT(*)\nFROM\n  public.m_countbycrc\nGROUP BY\n  time\n"
    }
   ]
  },
  {
   "title": "Calls in progress",
   "type": "graph",
   "gridPos": { "h": 10, "w": 9, "x": 5, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  value\nFROM m_callsinprogress\nGROUP BY time, value\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Total count (m_countbycrc)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 10, "x": 14, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroup(timestamp, '1h'),\n  count(*)\nFROM\n  m_countbycrc\nWHERE\n  $__timeFilter(timestamp)\ngroup by 1\norder by 1"
    }
   ]
  },
  {
   "title": "Total count (m_countbycrc)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT timestamp as time,\n  COUNT(*)\nFROM\n  public.m_countbycrc\nGROUP BY time\n"
    }
   ]
  },
  {
   "title": "Total count (m_durationbytg)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT timestamp as time,\n  COUNT(*)\nFROM\n  public.m_durationbytg\nGROUP BY time\n"
    }
   ]
  }
 ]
}