{
 "title": "CDRPR_SIMULATOR",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Queue size",
   "type": "graph",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "cdrpr_queue_size", "legendFormat": "Current" },
    {
     "expr": "avg_over_time(cdrpr_queue_size[5m])",
     "legendFormat": "5 min avg"
    }
   ]
  },
  {
   "title": "Generated calls per second",
   "type": "graph",
   "gridPos": { "h": 9, "w": 13, "x": 11, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(cdrpr_cdrs_generated_total[5m]))"
    }
   ]
  },
  {
   "title": "Queue utilization",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cdrpr_queue_size / cdrpr_max_queue_size * 100"
    }
   ]
  },
  {
   "title": "Total generated CDRs",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 5, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(cdrpr_cdrs_generated_total)"
    }
   ]
  },
  {
   "title": "Calls in progress",
   "type": "graph",
   "gridPos": { "h": 4, "w": 7, "x": 11, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "cdrpr_calls_in_progress" }
   ]
  },
  {
   "title": "Bulk size",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "cdrpr_bulk_size" }
   ]
  },
  {
   "title": "Calls in progress",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 11, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "cdrpr_calls_in_progress" }
   ]
  },
  {
   "title": "Simulator threads",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 5, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count(cdrpr_cdrs_generated_total) by (threadId))"
    }
   ]
  }
 ]
}