{
 "title": "MetricsLib Internals",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "Node",
    "query": "label_values(metricslib_servlet_requests_total, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Number of metrics in registries",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "metricslib_metrics_total{instance=\"$node\"}",
     "legendFormat": "[{{registry}}] {{metric}}"
    }
   ]
  },
  {
   "title": "Client requests",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(metricslib_attempted_requests_total{instance=\"$node\"}[5m])) by (endpoint) * 15",
     "legendFormat": "{{endpoint}}"
    },
    {
     "expr": "-1 * sum(irate(metricslib_failed_requests_total{instance=\"$node\",error!=\"null\"}[5m])) * 15",
     "legendFormat": "Failed"
    }
   ]
  },
  {
   "title": "Dropped metrics",
   "type": "graph",
   "description": "Metrics are dropped when they cannot be stored. If you see this graph, then you are losing data.",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(metricslib_dropped_metrics_total{instance=\"$node\"}[5m])) * 15",
     "legendFormat": "Dropped bulks"
    }
   ]
  },
  {
   "title": "Servlet requests",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(metricslib_servlet_requests_total{instance=\"$node\"}[5m])) by (uri) * 15",
     "legendFormat": "URI: {{uri}}"
    }
   ]
  },
  {
   "title": "Bulk insert time (avg over last 5 min)",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(metricslib_http_request_time_sum{instance=\"$node\"}[5m])) by (metric) / sum(rate(metricslib_http_request_time_count{instance=\"$node\"}[5m])) by (metric)",
     "legendFormat": "{{metric}}"
    }
   ]
  },
  {
   "title": "Success rate",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(sum(metricslib_attempted_requests_total{instance=\"$node\"}) - sum(metricslib_failed_requests_total{instance=\"$node\"})) / sum(metricslib_attempted_requests_total{instance=\"$node\"})"
    }
   ]
  },
  {
   "title": "Up time",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 13 },
   "format": "dateTimeFromNow",
   "valueName": "current",
   "targets": [
    {
     "expr": "metricslib_up_time{instance=\"$node\"}"
    }
   ]
  },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1 - (sum(rate(metricslib_failed_requests_total{instance=\"$node\"}[1m])) / sum(rate(metricslib_attempted_requests_total{instance=\"$node\"}[1m])))"
    }
   ]
  },
  {
   "title": "Distribution of request durations",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "sum(increase(metricslib_http_request_time_bucket{instance=\"$node\",le!=\"+Inf\"}[5m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Percentage of request durations below 100ms",
   "type": "graph",
   "description": "You might have an SLA to serve 95% of requests within 100ms. In that case, configure a histogram to have a bucket with an upper limit of 0.3 seconds. You can then directly express the relative amount of requests served within 300ms and easily alert if the value drops below 0.95.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(metricslib_http_request_time_bucket{instance=\"$node\",le=\"0.1\"}[5m])) by (metric) / sum(rate(metricslib_http_request_time_count{instance=\"$node\"}[5m])) by (metric)",
     "legendFormat": "{{metric}}"
    }
   ]
  },
  {
   "title": "Request by duration",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(metricslib_http_request_time_bucket{instance=\"$node\",le!=\"+Inf\"}) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Dump stats",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(rate(metricslib_dump_to_file_total{instance=\"$node\"}[5m])) * 15",
     "legendFormat": "Dumps"
    },
    {
     "expr": "sum(rate(metricslib_dump_files_uploads_total{instance=\"$node\"}[5m])) * -15",
     "legendFormat": "Uploads"
    }
   ]
  },
  {
   "title": "Request duration within which you have served N% of requests",
   "type": "graph",
   "description": "This time, you do not want to display the percentage of requests served within 300ms, but instead the 95th percentile, i.e. the request duration within which you have served 95% of requests. To do that, you can either configure a summary with a 0.95-quantile and (for example) a 5-minute decay time, or you configure a histogram with a few buckets around the 300ms mark",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(metricslib_http_request_time_bucket{instance=\"$node\"}[5m])) by (le))",
     "legendFormat": "50%"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(metricslib_http_request_time_bucket{instance=\"$node\"}[5m])) by (le))",
     "legendFormat": "75%"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(metricslib_http_request_time_bucket{instance=\"$node\"}[5m])) by (le))",
     "legendFormat": "95%"
    }
   ]
  },
  {
   "title": "Request duration histogram",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(metricslib_http_request_time_bucket{instance=\"$node\"}) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Percentage of metrics by registry",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 38 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(metricslib_metrics_total{instance=\"$node\"}) by (registry)",
     "legendFormat": "{{registry}}"
    }
   ]
  }
 ]
}