{
 "title": "MetricsLib Internals",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "metricslib_metrics_total",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "metricslib_metrics_total", "legendFormat": "[{{registry}}] {{metric}}" }
   ]
  },
  {
   "title": "metricslib_attempted_requests_total",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(metricslib_attempted_requests_total[5m])) by (endpoint) * 15",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "Fail rate",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum(metricslib_failed_requests_total) / sum(metricslib_attempted_requests_total)"
    }
   ]
  },
  {
   "title": "Average method time",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(rate(metricslib_bulk_request_time_sum[5m])) by (metric) / sum(rate(metricslib_bulk_request_time_count[5m])) by (metric)",
     "legendFormat": "{{metric}}"
    }
   ]
  },
  {
   "title": "Percentage of metrics by registry",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 13 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(metricslib_metrics_total) by (registry)",
     "legendFormat": "{{registry}}"
    }
   ]
  }
 ]
}