{
 "title": "MetricsLib Internals",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "Node",
    "query": "label_values(metricslib_servlet_requests_total, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Number of metrics in registries",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "metricslib_metrics_total{instance=\"$node\"}",
     "legendFormat": "[{{registry}}] {{metric}}"
    }
   ]
  },
  {
   "title": "Return code",
   "type": "graph",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(metricslib_http_requests_total{instance=\"$node\"}[5m])) by (code) * 15",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Dump stats",
   "type": "graph",
   "description": "Metrics that could not be inserted and were dumped to file. Number of dumped files per minute. Chart also shows number of uploaded files per minute.",
   "gridPos": { "h": 4, "w": 6, "x": 7, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(metricslib_dump_to_file_total{instance=\"$node\"}[5m])) * 60",
     "legendFormat": "Dumps"
    },
    {
     "expr": "sum(rate(metricslib_dump_files_uploads_total{instance=\"$node\",status=\"success\"}[5m])) * -60",
     "legendFormat": "Uploads (Success)"
    },
    {
     "expr": "sum(rate(metricslib_dump_files_uploads_total{instance=\"$node\",status=\"failed\"}[5m])) * -60",
     "legendFormat": "Uploads (Failed)"
    }
   ]
  },
  {
   "title": "Alarms sent",
   "type": "graph",
   "gridPos": { "h": 4, "w": 5, "x": 13, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(metricslib_alarms_sent_total{instance=\"$node\"}[5m])) * 15"
    }
   ]
  },
  {
   "title": "Servlet requests",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(metricslib_servlet_requests_total{instance=\"$node\"}[5m])) by (uri) * 15",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "Bulk insert time (avg over last 5 min)",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(metricslib_http_request_duration_seconds_sum{instance=\"$node\",metric!=\"null\"}[5m])) by (metric) / sum(rate(metricslib_http_request_duration_seconds_count{instance=\"$node\",metric!=\"null\"}[5m])) by (metric)",
     "legendFormat": "{{metric}}"
    }
   ]
  },
  {
   "title": "Success rate",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(sum(rate(metricslib_http_requests_total{instance=\"$node\",code=~\"^2.*$\"}[5m]))) / sum(rate(metricslib_http_requests_total{instance=\"$node\"}[5m]))"
    }
   ]
  },
  {
   "title": "Files waiting",
   "type": "stat",
   "description": "Current number of dumped files waiting to be uploaded",
   "gridPos": { "h": 4, "w": 2, "x": 15, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "metricslib_files_waiting_for_upload"
    }
   ]
  },
  {
   "title": "Last total insert time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 17, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(metricslib_http_request_duration_seconds_sum{instance=\"$node\",metric!=\"null\"}[5m])) * 15"
    }
   ]
  },
  {
   "title": "Up time",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 19, "y": 11 },
   "format": "dateTimeFromNow",
   "valueName": "current",
   "targets": [
    {
     "expr": "metricslib_up_time{instance=\"$node\"}"
    }
   ]
  },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(rate(metricslib_http_requests_total{instance=\"$node\",code=~\"^2.*$\"}[5m]))) / sum(rate(metricslib_http_requests_total{instance=\"$node\"}[5m]))"
    }
   ]
  },
  {
   "title": "Distribution of request durations",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "expr": "sum(increase(metricslib_http_request_duration_seconds_bucket{instance=\"$node\",le!=\"+Inf\"}[5m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Request duration within which you have served N% of requests",
   "type": "graph",
   "description": "This time, you do not want to display the percentage of requests served within 300ms, but instead the 95th percentile, i.e. the request duration within which you have served 95% of requests. To do that, you can either configure a summary with a 0.95-quantile and (for example) a 5-minute decay time, or you configure a histogram with a few buckets around the 300ms mark",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(metricslib_http_request_duration_seconds_bucket{instance=\"$node\"}[5m])) by (le))",
     "legendFormat": "50%"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(metricslib_http_request_duration_seconds_bucket{instance=\"$node\"}[5m])) by (le))",
     "legendFormat": "75%"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(metricslib_http_request_duration_seconds_bucket{instance=\"$node\"}[5m])) by (le))",
     "legendFormat": "95%"
    }
   ]
  },
  {
   "title": "Request by duration",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(metricslib_http_request_duration_seconds_bucket{instance=\"$node\",le!=\"+Inf\"}) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Client requests",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(metricslib_http_requests_total{instance=\"$node\"}[5m])) by (method) * 15",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Dropped metrics",
   "type": "graph",
   "description": "Metrics are dropped when they cannot be stored. If you see this graph, then you are losing data.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(metricslib_dropped_metrics_total{instance=\"$node\"}[5m])) * 15",
     "legendFormat": "Dropped bulks"
    }
   ]
  },
  {
   "title": "Request duration histogram",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(metricslib_http_request_duration_seconds_bucket{instance=\"$node\"}) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Percentage of metrics by registry",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 35 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(metricslib_metrics_total{instance=\"$node\"}) by (registry)",
     "legendFormat": "{{registry}}"
    }
   ]
  },
  {
   "title": "Endpoint requests",
   "type": "graph",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(metricslib_http_requests_total{instance=\"$node\"}[5m])) by (endpoint, method) * 15",
     "legendFormat": "{{method}} {{endpoint}}"
    }
   ]
  }
 ]
}