{
 "title": "CdrParser",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Processed files",
   "type": "graph",
   "gridPos": { "h": 9, "w": 18, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(cdrparser_processed_files_total[5m]) * 15"
    }
   ]
  },
  {
   "title": "Total processed files",
   "type": "stat",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cdrparser_processed_files_total"
    }
   ]
  },
  {
   "title": "Processed records",
   "type": "graph",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(cdrparser_records_total[5m])",
     "legendFormat": "{{fileType}}"
    }
   ]
  },
  {
   "title": "Total processed records",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "cdrparser_records_total", "legendFormat": "{{fileType}}" }
   ]
  }
 ]
}