version: '3.6'

networks:
  net:
    #driver: bridge
    #driver: overlay
    #attachable: true

configs:
  kibana_config:
    file: ./kibana.yml

services:

  kibana:
    image: docker.elastic.co/kibana/kibana:7.9.2
    networks:
      - net
    ports:
      - 5601:5601
    configs:
      - source: kibana_config
        target: /usr/share/kibana/config/kibana.yml
    environment:
      SERVER_NAME: kibana.example.org
      ELASTICSEARCH_URL: http://192.168.0.171:9200
      ELASTICSEARCH_HOSTS: http://192.168.0.171:9200
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.hostname == mcrk-docker-2
